
services:
  db:
    image: postgres:16-alpine
    container_name: riftea-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: riftea
    ports:
      - "5432:5432" # si choca, cambiá a "5433:5432"
    volumes:
      - riftea_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d riftea || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  riftea_pg_data:
